"""add transactions accounts

Revision ID: 09da9c99d25d
Revises: 9c361e80917c
Create Date: 2025-11-11 14:35:13.265898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09da9c99d25d'
down_revision: Union[str, Sequence[str], None] = '9c361e80917c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('max_bid_one_time', sa.Float(), nullable=False),
    sa.Column('bid_power', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_plan_id'), 'user_account', ['plan_id'], unique=False)
    op.create_index('ix_user_account_user_plan', 'user_account', ['user_uuid', 'plan_id'], unique=False)
    op.create_index(op.f('ix_user_account_user_uuid'), 'user_account', ['user_uuid'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('PLAN_PURCHASE', 'BID_PLACEMENT', 'ADJUSTMENT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_account_type', 'transaction', ['user_account_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_transaction_plan_id'), 'transaction', ['plan_id'], unique=False)
    op.create_index(op.f('ix_transaction_user_account_id'), 'transaction', ['user_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_account_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_plan_id'), table_name='transaction')
    op.drop_index('ix_transaction_account_type', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_user_account_user_uuid'), table_name='user_account')
    op.drop_index('ix_user_account_user_plan', table_name='user_account')
    op.drop_index(op.f('ix_user_account_plan_id'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('plan')
    # ### end Alembic commands ###
