"""update payment table

Revision ID: 9c361e80917c
Revises: e14844ed736e
Create Date: 2025-08-27 16:17:56.979844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c361e80917c'
down_revision: Union[str, Sequence[str], None] = 'e14844ed736e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', recreate='auto') as batch_op:
        batch_op.alter_column(
            'purpose',
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            'purpose_external_id',
            existing_type=sa.INTEGER(),
            type_=sa.String(),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', recreate='auto') as batch_op:
        batch_op.alter_column(
            'purpose_external_id',
            existing_type=sa.String(),
            type_=sa.INTEGER(),
            nullable=True,
        )
        batch_op.alter_column(
            'purpose',
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
    # ### end Alembic commands ###
