"""init

Revision ID: dc15df552fea
Revises: 
Create Date: 2025-06-24 14:20:26.730038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc15df552fea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_external_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_source'), 'payment', ['source'], unique=False)
    op.create_index(op.f('ix_payment_user_external_id'), 'payment', ['user_external_id'], unique=False)
    op.create_index('ix_provider_payment_id', 'payment', ['provider', 'provider_payment_id'], unique=False)
    op.create_index('ix_user_source', 'payment', ['user_external_id', 'source'], unique=False)
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transaction')
    op.drop_index('ix_user_source', table_name='payment')
    op.drop_index('ix_provider_payment_id', table_name='payment')
    op.drop_index(op.f('ix_payment_user_external_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_source'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
